# Generated by Django 5.2.6 on 2025-10-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
