# Generated by Django 5.2.6 on 2026-02-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectproposal_rejection_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
