# Generated by Django 5.2.6 on 2026-03-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(default='CS', max_length=50),
            preserve_default=False,
        ),
    ]
