# Generated by Django 5.2.6 on 2026-03-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='required_experience',
            field=models.CharField(choices=[('ANY', 'Any Experience (All)'), ('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], default='ANY', max_length=20),
        ),
    ]
