# Generated by Django 5.2.6 on 2025-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/profile_images/'),
        ),
    ]
