# Generated by Django 5.2.6 on 2025-10-16 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancer', '0001_initial'),
        ('projects', '0001_initial'),
        ('startup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerearning',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerearning',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='freelancer.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='freelancer.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='freelancerrating',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='freelancer.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='freelancerrating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_ratings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='freelancerrating',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_ratings', to='startup.startupprofile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='freelancer.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='freelancer.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='freelancer.freelancerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='freelancerrating',
            unique_together={('freelancer', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('freelancer', 'name')},
        ),
    ]
