# Generated by Django 5.2.6 on 2025-10-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
