# Generated by Django 5.2.6 on 2025-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_portfolioitem_live_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_files/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
    ]
