# Generated by Django 5.2.6 on 2025-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/images/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/files/'),
        ),
    ]
