# Generated by Django 5.2.6 on 2025-12-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_alter_freelancerprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerearning',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancerearning',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='freelancerrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='freelancerrating',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelancerrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='freelancerrating',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='freelancer',
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skill',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='FreelancerEarning',
        ),
        migrations.DeleteModel(
            name='FreelancerRating',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
