# Generated by Django 5.2.6 on 2026-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_remove_freelancerearning_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancerprofile',
            options={},
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='domain',
            field=models.CharField(default='CS', max_length=50),
            preserve_default=False,
        ),
    ]
