# Generated by Django 5.2.6 on 2026-03-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_alter_freelancerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='experience_years',
            field=models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], default='0-1', max_length=20),
        ),
    ]
