# Generated by Django 5.2.6 on 2026-03-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_freelancerprofile_experience_years'),
        ('projects', '0005_project_required_experience'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='FreelancerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeliness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('communication_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='freelancer.freelancerprofile')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='projects.project')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_ratings', to='startup.startupprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
