# Generated by Django 5.2.6 on 2026-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_remove_freelancerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
