# Generated by Django 5.2.6 on 2026-03-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_milestone_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='ai_verification_report',
            field=models.TextField(blank=True, help_text='AI-generated verification reasoning', null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload your certificate (image or PDF)', null=True, upload_to='freelancer/certificates/'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='fraud_score',
            field=models.IntegerField(default=0, help_text='0 = trustworthy, 100 = likely fraudulent'),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to your GitHub profile', null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('SUSPICIOUS', 'Suspicious'), ('UNVERIFIED', 'Unverified')], default='PENDING', max_length=20),
        ),
    ]
